### ISSUE TITLE
## As Rodrigo checking out a new bulletin board, I want to view a blank board so that I can see what the bulletins will be posted to.

### ISSUE THREAD

**Issue by egd1753** [egd1753/upost#1]
![Screenshot from 2019-07-29 15-35-37](https://user-images.githubusercontent.com/43823026/62087625-055e1a80-b228-11e9-9bb2-a5c32310ff84.png)

#### Tasks:
- [x] Create a new uPost repo and link it to this project
- [x] Generate a new Rails application
- [x] Create a README.md
- [x] Create a development database
- [x] Add Rspec gem
- [x] Create Welcome controller/views (Index, About)
- [x] Configure router for Welcome
- [x] Write tests for Welcome controller
- [x] Add Bootstrap gem
- [x] Generate a board model
- [x] Generate a board controller/view
- [x] Configure router for board controller/view
- [x] Push changes to remote repo
