### ISSUE TITLE
## As Betty, I want to be able to create a new blank bulletin board for Beanz, so we can have our own uPost board.

### ISSUE THREAD

**Issue by egd1753** [egd1753/upost#11]
#### Tasks: 
- [x] Create a model for boards
- [x] Add Shoulda matchers gem for Rspec
- [x] Write tests
- [x] Create a `has_many :bulletins` association in board model
- [x] Create a `belongs_to :boards` association in bulletin model
- [x] Configure router
- [x] Refactor views so board#show and AddBulletin link aren't broken
- [x] Push changes to GH
