### ISSUE TITLE
## As Rodrigo, I want to the site to be stylish and pretty to look at so that I have a more pleasant experience

### ISSUE THREAD

**Issue by egd1753** [egd1753/upost#17]
#### Tasks:
- [ ] Review Bootstrap
- [ ] Convert project from Bootstrap 3 to 4 if necessary
- [ ] Create a unifying color theme and apply to the entire project
- [ ] Create a Welcome index page
- [ ] Create About page
- [ ] Create a more stylish board page (maybe different board image, buttons, etc.)
- [ ] Fix the bulletins #create page
- [ ] Push changes to GH
