### ISSUE TITLE
## As Rodrigo, I want to be able to create a bulletin using a  template so that I can quickly and easily get my message out there.

### ISSUE THREAD

**Issue by egd1753** [egd1753/upost#2]
![New bulletin](https://user-images.githubusercontent.com/43823026/62087716-58d06880-b228-11e9-93cb-676171d7dcec.png)

#### Tasks: 
- [x] Write tests
- [x] Generate bulletin New view
- [x] Generate a bulletin controller with CRUD actions New and Create
- [x] Configure "Add Bulletin" button link
- [x] Configure routing
- [x] Push changes to GH
