### ISSUE TITLE
## As Rodrigo, I want my created bulletins to be persisted in a database so they can be accessed and viewed later.

### ISSUE THREAD

**Issue by egd1753** [egd1753/upost#3]
![Bulletin show view](https://user-images.githubusercontent.com/43823026/62089249-e5315a00-b22d-11e9-8a80-17fd12ff628b.png)

#### Tasks: 
- [x] Generate a bulletin model
- [x] Write tests
- [x] Push change to GH
- [x] Deploy to Heroku
