### ISSUE TITLE
## As Rodrigo, I want the bulletin board to display my bulletins in a simple, auto-configured way so that I can post my bulletin and go on about my day.

### ISSUE THREAD

**Issue by egd1753** [egd1753/upost#4]
![Bulletin index view on board](https://user-images.githubusercontent.com/43823026/62087760-84ebe980-b228-11e9-8835-4d822bf432ff.png)

#### Tasks: 
- [x] Write tests for index view/index controller
- [x] Create Index view for bulletins
- [x] Create Index action in bulletin controller
- [x] Configure routing
- [x] Style bulletins 
- [x] Display bulletins on top of board
- [x] Push changes to GH

**Comment by egd1753** [comment]
Should associate board and bulletin models before I finish
