### ISSUE TITLE
## As Rodrigo, I want to be able to edit or delete a bulletin that I made so that I can change or take the bulletin down if I changed my mind.

### ISSUE THREAD

**Issue by egd1753** [egd1753/upost#5]
#### Tasks:
- [ ] Write tests
- [ ] Create Edit view for bulletin
- [ ] Create bulletin controller CRUD actions for Edit and Delete
- [ ] Setup routing
- [ ] Push changes to GH
- [ ] Deploy to Heroku
