### ISSUE TITLE
## As Rodrigo, I want to be able to create a user profile so that I can have a simple profile that shows all my bulletins, and have my username show up under bulletins that I've made.

### ISSUE THREAD

**Issue by egd1753** [egd1753/upost#6]
#### Tasks:
- [ ] Write tests
- [ ] Install Devise gem
- [ ] Generate a devise user model
- [ ] Generate a user controller
- [ ] Create a `has_many :bulletins` association in user model
- [ ] Create a `belongs_to :user` association in bulletin model
- [ ] Configure router
- [ ] Push changes to GH
- [ ] Deploy to Heroku
